// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  id_grabber_form: dynamic(() => import("./IdGrabberForm")),
  image_block: dynamic(() => import("./ImageBlock")),
  rich_text: dynamic(() => import("./RichText")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
  video_slice: dynamic(() => import("./VideoSlice")),
};
